# Generated by Django 4.0.1 on 2022-01-21 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_code', models.CharField(editable=False, max_length=15, unique=True)),
                ('name', models.CharField(max_length=15)),
                ('pes_id', models.CharField(max_length=11, unique=True)),
                ('whats_app', models.CharField(max_length=10, unique=True)),
                ('team_photo', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(max_length=9)),
                ('is_active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tournament_name', models.TextField(max_length=10)),
                ('tournament_type', models.CharField(default='', max_length=10)),
                ('total_players', models.IntegerField(default=0)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('runners_up', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='runners_up', to='api.player')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Season', to='api.season')),
                ('second_runners_up', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='second_runners_up', to='api.player')),
                ('top_Goal_Scorer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='top_goal_scorer', to='api.player')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='winner', to='api.player')),
            ],
        ),
    ]
