# Generated by Django 4.0.1 on 2022-01-21 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_tournament_tournament_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='tournament_name',
            field=models.CharField(max_length=20),
        ),
    ]
