# Generated by Django 4.0.1 on 2022-01-21 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_tournament_tournament_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
